language: go
go:
 - 1.x

cache:
  directories:
  - $HOME/.cache/go-build
  - $GOPATH/pkg/mod

install: true

script:
  - go build ./...
  - ./hack/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
