language: go
go:
 - 1.x

go_import_path: kubedb.dev/cli

env:
  global:
  - GOFLAGS=-mod=vendor
  - GO111MODULE=on

cache:
  directories:
  - $HOME/.cache/go-build
  - $GOPATH/pkg/mod

install: true

script:
  - go build ./...
  - ./hack/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
