apiVersion: v1
description: 'KubeDB by AppsCode - Production ready databases on Kubernetes'
name: kubedb
version: 0.9.0-beta.1
appVersion: 0.9.0-beta.1
home: https://github.com/kubedb/cli
icon: https://cdn.appscode.com/images/icon/kubedb.png
sources:
  - https://github.com/kubedb/cli
maintainers:
  - name: appscode
    email: kubedb@appscode.com
