{{ if .Values.catalog.elasticsearch }}
---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "5.6"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "5.6"
  db:
    image: "{{ .Values.dockerRegistry }}/elasticsearch:5.6"
  exporter:
    image: "{{ .Values.dockerRegistry }}/operator:0.8.0"
  tools:
    image: "{{ .Values.dockerRegistry }}/elasticsearch-tools:5.6"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "5.6-v1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "5.6"
  db:
    image: "{{ .Values.dockerRegistry }}/elasticsearch:5.6-v1"
  exporter:
    image: "{{ .Values.dockerRegistry }}/elasticsearch_exporter:1.0.2"
  tools:
    image: "{{ .Values.dockerRegistry }}/elasticsearch-tools:5.6-v2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "5.6.4"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "5.6.4"
  db:
    image: "{{ .Values.dockerRegistry }}/elasticsearch:5.6.4"
  exporter:
    image: "{{ .Values.dockerRegistry }}/operator:0.8.0"
  tools:
    image: "{{ .Values.dockerRegistry }}/elasticsearch-tools:5.6.4"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "5.6.4-v1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "5.6.4"
  db:
    image: "{{ .Values.dockerRegistry }}/elasticsearch:5.6.4-v1"
  exporter:
    image: "{{ .Values.dockerRegistry }}/elasticsearch_exporter:1.0.2"
  tools:
    image: "{{ .Values.dockerRegistry }}/elasticsearch-tools:5.6.4-v2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "6.2.4"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "6.2.4"
  db:
    image: "{{ .Values.dockerRegistry }}/elasticsearch:6.2.4"
  exporter:
    image: "{{ .Values.dockerRegistry }}/operator:0.8.0"
  tools:
    image: "{{ .Values.dockerRegistry }}/elasticsearch-tools:6.2.4"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "6.2.4-v1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "6.2.4"
  db:
    image: "{{ .Values.dockerRegistry }}/elasticsearch:6.2.4-v1"
  exporter:
    image: "{{ .Values.dockerRegistry }}/elasticsearch_exporter:1.0.2"
  tools:
    image: "{{ .Values.dockerRegistry }}/elasticsearch-tools:6.2.4-v2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "6.2"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "6.2"
  db:
    image: "{{ .Values.dockerRegistry }}/elasticsearch:6.2"
  exporter:
    image: "{{ .Values.dockerRegistry }}/operator:0.8.0"
  tools:
    image: "{{ .Values.dockerRegistry }}/elasticsearch-tools:6.2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "6.2-v1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "6.2"
  db:
    image: "{{ .Values.dockerRegistry }}/elasticsearch:6.2-v1"
  exporter:
    image: "{{ .Values.dockerRegistry }}/elasticsearch_exporter:1.0.2"
  tools:
    image: "{{ .Values.dockerRegistry }}/elasticsearch-tools:6.2-v2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "6.3.0"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "6.3.0"
  db:
    image: "{{ .Values.dockerRegistry }}/elasticsearch:6.3.0"
  exporter:
    image: "{{ .Values.dockerRegistry }}/operator:0.8.0"
  tools:
    image: "{{ .Values.dockerRegistry }}/elasticsearch-tools:6.3.0"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "6.3.0-v1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "6.3.0"
  db:
    image: "{{ .Values.dockerRegistry }}/elasticsearch:6.3.0-v1"
  exporter:
    image: "{{ .Values.dockerRegistry }}/elasticsearch_exporter:1.0.2"
  tools:
    image: "{{ .Values.dockerRegistry }}/elasticsearch-tools:6.3.0-v2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "6.3"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "6.3"
  db:
    image: "{{ .Values.dockerRegistry }}/elasticsearch:6.3"
  exporter:
    image: "{{ .Values.dockerRegistry }}/operator:0.8.0"
  tools:
    image: "{{ .Values.dockerRegistry }}/elasticsearch-tools:6.3"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "6.3-v1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "6.3"
  db:
    image: "{{ .Values.dockerRegistry }}/elasticsearch:6.3-v1"
  exporter:
    image: "{{ .Values.dockerRegistry }}/elasticsearch_exporter:1.0.2"
  tools:
    image: "{{ .Values.dockerRegistry }}/elasticsearch-tools:6.3-v2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "6.4.0"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "6.4.0"
  db:
    image: "{{ .Values.dockerRegistry }}/elasticsearch:6.4.0"
  exporter:
    image: "{{ .Values.dockerRegistry }}/elasticsearch_exporter:1.0.2"
  tools:
    image: "{{ .Values.dockerRegistry }}/elasticsearch-tools:6.4.0-v1"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "6.4"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "6.4"
  db:
    image: "{{ .Values.dockerRegistry }}/elasticsearch:6.4"
  exporter:
    image: "{{ .Values.dockerRegistry }}/elasticsearch_exporter:1.0.2"
  tools:
    image: "{{ .Values.dockerRegistry }}/elasticsearch-tools:6.4-v1"

{{ end }}
