{{ if .Values.catalog.postgres }}
---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "9.6"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "9.6"
  db:
    image: "{{ .Values.dockerRegistry }}/postgres:9.6"
  exporter:
    image: "{{ .Values.dockerRegistry }}/operator:0.8.0"
  tools:
    image: "{{ .Values.dockerRegistry }}/postgres-tools:9.6"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "9.6-v1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "9.6"
  db:
    image: "{{ .Values.dockerRegistry }}/postgres:9.6-v2"
  exporter:
    image: "{{ .Values.dockerRegistry }}/postgres_exporter:v0.4.6"
  tools:
    image: "{{ .Values.dockerRegistry }}/postgres-tools:9.6-v2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "9.6.7"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "9.6.7"
  db:
    image: "{{ .Values.dockerRegistry }}/postgres:9.6.7"
  exporter:
    image: "{{ .Values.dockerRegistry }}/operator:0.8.0"
  tools:
    image: "{{ .Values.dockerRegistry }}/postgres-tools:9.6.7"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "9.6.7-v1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "9.6.7"
  db:
    image: "{{ .Values.dockerRegistry }}/postgres:9.6.7-v2"
  exporter:
    image: "{{ .Values.dockerRegistry }}/postgres_exporter:v0.4.6"
  tools:
    image: "{{ .Values.dockerRegistry }}/postgres-tools:9.6.7-v2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "10.2"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "10.2"
  db:
    image: "{{ .Values.dockerRegistry }}/postgres:10.2"
  exporter:
    image: "{{ .Values.dockerRegistry }}/operator:0.8.0"
  tools:
    image: "{{ .Values.dockerRegistry }}/postgres-tools:10.2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "10.2-v1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "10.2"
  db:
    image: "{{ .Values.dockerRegistry }}/postgres:10.2-v2"
  exporter:
    image: "{{ .Values.dockerRegistry }}/postgres_exporter:v0.4.6"
  tools:
    image: "{{ .Values.dockerRegistry }}/postgres-tools:10.2-v2"

---
# After 0.9.0

apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "9.6-v2"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "9.6"
  db:
    image: "{{ .Values.dockerRegistry }}/postgres:9.6-v3"
  exporter:
    image: "{{ .Values.dockerRegistry }}/postgres_exporter:v0.4.7"
  tools:
    image: "{{ .Values.dockerRegistry }}/postgres-tools:9.6-v2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "9.6.7-v2"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "9.6.7"
  db:
    image: "{{ .Values.dockerRegistry }}/postgres:9.6.7-v3"
  exporter:
    image: "{{ .Values.dockerRegistry }}/postgres_exporter:v0.4.7"
  tools:
    image: "{{ .Values.dockerRegistry }}/postgres-tools:9.6.7-v2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "10.2-v2"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "10.2"
  db:
    image: "{{ .Values.dockerRegistry }}/postgres:10.2-v3"
  exporter:
    image: "{{ .Values.dockerRegistry }}/postgres_exporter:v0.4.7"
  tools:
    image: "{{ .Values.dockerRegistry }}/postgres-tools:10.2-v2"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "10.6"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "10.6"
  db:
    image: "{{ .Values.dockerRegistry }}/postgres:10.6"
  exporter:
    image: "{{ .Values.dockerRegistry }}/postgres_exporter:v0.4.7"
  tools:
    image: "{{ .Values.dockerRegistry }}/postgres-tools:10.6"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "11.1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "11.1"
  db:
    image: "{{ .Values.dockerRegistry }}/postgres:11.1"
  exporter:
    image: "{{ .Values.dockerRegistry }}/postgres_exporter:v0.4.7"
  tools:
    image: "{{ .Values.dockerRegistry }}/postgres-tools:11.1"
{{ end }}
