{{ if .Values.catalog.redis }}
---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "4"
  db:
    image: "{{ .Values.dockerRegistry }}/redis:4"
  exporter:
    image: "{{ .Values.dockerRegistry }}/operator:0.8.0"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4-v1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "4"
  db:
    image: "{{ .Values.dockerRegistry }}/redis:4-v1"
  exporter:
    image: "{{ .Values.dockerRegistry }}/redis_exporter:v0.21.1"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4.0"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "4.0"
  db:
    image: "{{ .Values.dockerRegistry }}/redis:4.0"
  exporter:
    image: "{{ .Values.dockerRegistry }}/operator:0.8.0"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4.0-v1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "4.0"
  db:
    image: "{{ .Values.dockerRegistry }}/redis:4.0-v1"
  exporter:
    image: "{{ .Values.dockerRegistry }}/redis_exporter:v0.21.1"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4.0.6"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "4.0.6"
  db:
    image: "{{ .Values.dockerRegistry }}/redis:4.0.6"
  exporter:
    image: "{{ .Values.dockerRegistry }}/operator:0.8.0"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4.0.6-v1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "4.0.6"
  db:
    image: "{{ .Values.dockerRegistry }}/redis:4.0.6-v1"
  exporter:
    image: "{{ .Values.dockerRegistry }}/redis_exporter:v0.21.1"

---
# After 0.9.0

apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4.0-v2"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "4.0"
  db:
    image: "{{ .Values.dockerRegistry }}/redis:4.0-v2"
  exporter:
    image: "{{ .Values.dockerRegistry }}/redis_exporter:v0.21.1"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4.0.6-v2"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "4.0.6"
  db:
    image: "{{ .Values.dockerRegistry }}/redis:4.0.6-v2"
  exporter:
    image: "{{ .Values.dockerRegistry }}/redis_exporter:v0.21.1"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "4.0.11"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "4.0.11"
  db:
    image: "{{ .Values.dockerRegistry }}/redis:4.0.11"
  exporter:
    image: "{{ .Values.dockerRegistry }}/redis_exporter:v0.21.1"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "5.0"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "5.0"
  db:
    image: "{{ .Values.dockerRegistry }}/redis:5.0"
  exporter:
    image: "{{ .Values.dockerRegistry }}/redis_exporter:v0.21.1"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "5.0-v1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "5.0"
  db:
    image: "{{ .Values.dockerRegistry }}/redis:5.0-v1"
  exporter:
    image: "{{ .Values.dockerRegistry }}/redis_exporter:v0.21.1"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "5.0.3"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "5.0.3"
  db:
    image: "{{ .Values.dockerRegistry }}/redis:5.0.3"
  exporter:
    image: "{{ .Values.dockerRegistry }}/redis_exporter:v0.21.1"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: RedisVersion
metadata:
  name: "5.0.3-v1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "5.0.3"
  db:
    image: "{{ .Values.dockerRegistry }}/redis:5.0.3-v1"
  exporter:
    image: "{{ .Values.dockerRegistry }}/redis_exporter:v0.21.1"
{{ end }}
