---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "3.4"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "3.4"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:3.4"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/operator:0.8.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:3.4"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "3.4-v1"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "3.4"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:3.4-v1"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongodb_exporter:v1.0.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:3.4-v2"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "3.6"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "3.6"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:3.6"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/operator:0.8.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:3.6"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "3.6-v1"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "3.6"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:3.6-v1"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongodb_exporter:v1.0.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:3.6-v2"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot

---
# After 0.9.0

apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "3.4-v2"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "3.4"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:3.4-v2"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongodb_exporter:v1.0.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:3.4-v2"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "3.6-v2"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "3.6"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:3.6-v2"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongodb_exporter:v1.0.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:3.6-v2"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "4.0.5"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "4.0.5"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:4.0.5"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongodb_exporter:v1.0.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:4.0.5"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "4.0"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "4.0.5"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:4.0"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongodb_exporter:v1.0.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:4.0"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "4.1.7"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "4.1.7"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:4.1.7"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongodb_exporter:v1.0.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:4.1.7"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot

---
# After 0.11.0

apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "3.4-v3"
  labels:
    app: kubedb
spec:
  version: "3.4"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:3.4-v3"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongodb_exporter:v1.0.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:3.4-v3"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "3.6-v3"
  labels:
    app: kubedb
spec:
  version: "3.6"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:3.6-v3"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongodb_exporter:v1.0.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:3.6-v3"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "4.0.5-v1"
  labels:
    app: kubedb
spec:
  version: "4.0.5"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:4.0.5-v1"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongodb_exporter:v1.0.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:4.0.5-v1"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "4.0-v1"
  labels:
    app: kubedb
spec:
  version: "4.0.5"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:4.0-v1"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongodb_exporter:v1.0.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:4.0-v1"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: "4.1.7-v1"
  labels:
    app: kubedb
spec:
  version: "4.1.7"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo:4.1.7-v1"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongodb_exporter:v1.0.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mongo-tools:4.1.7-v1"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot
