---
apiVersion: kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: "8.0"
  labels:
    app: kubedb
spec:
  version: "8.0"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql:8.0"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysqld-exporter:v0.11.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql-tools:8.0"

---
apiVersion: kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: "8"
  labels:
    app: kubedb
spec:
  version: "8"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql:8"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysqld-exporter:v0.11.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql-tools:8"

---
apiVersion: kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: "5.7"
  labels:
    app: kubedb
spec:
  version: "5.7"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql:5.7"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysqld-exporter:v0.11.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql-tools:5.7"

---
apiVersion: kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: "5"
  labels:
    app: kubedb
spec:
  version: "5"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql:5"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysqld-exporter:v0.11.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql-tools:5"
