---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: "5"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "5"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql:5"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/operator:0.8.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql-tools:5"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mysql-db
    snapshotterPolicyName: mysql-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: "5-v1"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "5"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql:5-v1"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysqld-exporter:v0.11.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql-tools:5-v2"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mysql-db
    snapshotterPolicyName: mysql-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: "5.7"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "5.7"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql:5.7"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/operator:0.8.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql-tools:5.7"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mysql-db
    snapshotterPolicyName: mysql-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: "5.7-v1"
  labels:
    app: kubedb
spec:
  version: "5.7"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql:5.7-v1"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysqld-exporter:v0.11.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql-tools:5.7-v2"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mysql-db
    snapshotterPolicyName: mysql-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: "8"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "8"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql:8"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/operator:0.8.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql-tools:8"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mysql-db
    snapshotterPolicyName: mysql-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: "8-v1"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "8"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql:8-v1"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysqld-exporter:v0.11.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql-tools:8-v2"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mysql-db
    snapshotterPolicyName: mysql-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: "8.0"
  labels:
    app: kubedb
spec:
  deprecated: true
  version: "8.0"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql:8.0"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/operator:0.8.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql-tools:8.0"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mysql-db
    snapshotterPolicyName: mysql-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: "8.0-v1"
  labels:
    app: kubedb
spec:
  version: "8.0"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql:8.0-v1"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysqld-exporter:v0.11.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql-tools:8.0-v2"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mysql-db
    snapshotterPolicyName: mysql-snapshot

---
# After 0.9.0

apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: "8.0-v2"
  labels:
    app: kubedb
spec:
  version: "8.0"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql:8.0-v2"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysqld-exporter:v0.11.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql-tools:8.0-v3"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mysql-db
    snapshotterPolicyName: mysql-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: "8.0.3"
  labels:
    app: kubedb
spec:
  version: "8.0.3"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql:8.0.3"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysqld-exporter:v0.11.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql-tools:8.0.3"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mysql-db
    snapshotterPolicyName: mysql-snapshot

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: "8.0.14"
  labels:
    app: kubedb
spec:
  version: "8.0.14"
  db:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql:8.0.14"
  exporter:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysqld-exporter:v0.11.0"
  tools:
    image: "${KUBEDB_DOCKER_REGISTRY}/mysql-tools:8.0.14"
  initContainer:
    image: "${KUBEDB_DOCKER_REGISTRY}/busybox"
  podSecurityPolicies:
    databasePolicyName: mysql-db
    snapshotterPolicyName: mysql-snapshot
